data:
  root_dir: "./wlasl_data/videos"
  json_file: "./wlasl_data/WLASL_v0.3_with_skeleton.json"  
  label_file: "./wlasl_data/wlasl_class_list.txt"
  subset: 100 

model:
  name: "DSLNet"
  num_classes: 100  
  in_channels: 3
  num_joints: 21

input:
  num_frames: 16    
  coord_normalize: true
  sampling_strategy: "even"  #均勻||連續

training:
  epochs: 120
  batch_size: 32     
  learning_rate: 0.001 
  weight_decay: 0.01
  warmup_epochs: 5    
  scheduler: "cosine"
  alpha_geo: 0.05     
  gradient_clip: 1.0

optimizer:
  name: "adamw"
  betas: [0.9, 0.999]
  eps: 1e-8
#這邊都沒用augmentation是怕破壞骨架結構
augmentation:
  random_rotate: false   
  random_scale: false    
  gaussian_noise: 0.001  
  temporal_stretch: false 

evaluation:
  top_k: [1, 5, 10] 

device: "auto"  

save:
  model_path: "./checkpoints/dslnet_wlasl_100_best.pth"
  checkpoint_freq: 20 

validation:
  freq: 1 
  early_stopping:
    patience: 25
    min_delta: 0.0001